'use strict';
// Clipboard recorder: polls the system clipboard and saves every new text / image / file copy into the workspace.
// Uses Electron's async (W3C-style) clipboard API: clipboard.read() → ClipboardItem[] with MIME types.
// Respects the "concealed" markers password managers put on the clipboard and can be switched off in settings.
const { clipboard } = require('electron');
const crypto = require('crypto');
const { fileURLToPath } = require('url');

const POLL_MS = 800;
// Formats that mean "do not record this" (1Password, KeePass, Bitwarden, macOS Keychain, ...)
const CONCEALED = ['ExcludeClipboardContentFromMonitorProcessing', 'org.nspasteboard.ConcealedType', 'org.nspasteboard.TransientType', 'org.nspasteboard.AutoGeneratedType'];

let deps = null;         // { store, workspace }
let timer = null;
let last = { sig: '', kind: '' };
let ignore = new Set();  // signatures the app itself put on the clipboard (its own screenshots)
let imagePolls = 0;
let busy = false;

const hash = (buf) => crypto.createHash('md5').update(buf).digest('hex');

/** What is on the clipboard right now: { types, files, text, png } (png is only read when an image is present). */
/**
 * What is on the clipboard right now: { types, files, text, png }.
 * `all` reads every shape rather than stopping at the first one that wins, which is how the poller
 * learns that a file and a bitmap are the same copy (see poll).
 */
async function snapshot({ readImage = true, all = false } = {}) {
  const items = await clipboard.read();
  const types = items.flatMap((i) => i.types);
  const out = { types, files: [], text: '', png: null };
  const item = items.find((i) => i.types.includes('text/uri-list'));
  if (item) {
    try {
      const list = Buffer.from(await (await item.getType('text/uri-list')).arrayBuffer()).toString('utf8');
      out.files = list.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.startsWith('file:')).map((l) => {
        try { return fileURLToPath(l); } catch (_) { return ''; }
      }).filter(Boolean);
    } catch (_) { /* ignore */ }
  }
  if (all || !out.files.length) {
    try { out.text = await clipboard.readText(); } catch (_) { out.text = ''; }
    if ((all || !out.text) && readImage) {
      const img = items.find((i) => i.types.includes('image/png'));
      if (img) {
        try { out.png = Buffer.from(await (await img.getType('image/png')).arrayBuffer()); } catch (_) { out.png = null; }
      }
    }
  }
  return out;
}

function signature(snap) {
  if (snap.files.length) return `files:${snap.files.join('|')}`;
  if (snap.text) return `text:${hash(snap.text)}`;
  if (snap.png) return `image:${hash(snap.png)}`;
  return '';
}

/** Every shape present, most preferred first. */
function signatures(snap) {
  const out = [];
  if (snap.files.length) out.push(`files:${snap.files.join('|')}`);
  if (snap.text) out.push(`text:${hash(snap.text)}`);
  if (snap.png) out.push(`image:${hash(snap.png)}`);
  return out;
}

// One copy can sit on the clipboard in several shapes at once: WeChat's screenshot leaves a temporary
// file beside the bitmap. We file one of them; the others are the same event, and when the app later
// withdraws the shape we filed, what is left would look like something new. So at the moment of
// filing, the shapes we did *not* take are noted down, and a poll that finds one of them lets it go.
// Only the ones not taken: copying the same thing again on purpose is a different event, and its own
// signature was never written down.
const OTHER_SHAPE_MS = 5 * 60 * 1000;
const otherShapes = new Map();   // signature -> when it was seen

function noteOtherShapes(snap, taken, now = Date.now()) {
  for (const [k, at] of otherShapes) if (now - at > OTHER_SHAPE_MS) otherShapes.delete(k);
  for (const sig of signatures(snap)) if (sig !== taken) otherShapes.set(sig, now);
}

function isOtherShape(sig, now = Date.now()) {
  const at = otherShapes.get(sig);
  if (at === undefined) return false;
  if (now - at > OTHER_SHAPE_MS) { otherShapes.delete(sig); return false; }
  otherShapes.delete(sig);       // one leftover, let go once
  return true;
}

/**
 * Tells the watcher to skip the next appearance of this exact content. Used when the app copies its own
 * screenshot to the clipboard, so one capture does not also become a clipboard entry.
 * Note: the clipboard re-encodes images, so the bytes we read back may differ from the bytes we wrote;
 * the poller therefore also treats the very next image after this call as ours.
 */
function ignoreNext(buf) {
  ignore.add(`image:${hash(buf)}`);
  ignore.add('image:*next*');
  setTimeout(() => { ignore.delete(`image:${hash(buf)}`); ignore.delete('image:*next*'); }, 15000);
}

function isConcealed(types) {
  return types.some((t) => CONCEALED.some((c) => t.includes(c)));
}

function start(d) {
  deps = d;
  stop();
  // ignore whatever is already on the clipboard when recording starts
  snapshot().then((snap) => { last = { sig: signature(snap), kind: '' }; }).catch(() => { last = { sig: '', kind: '' }; });
  timer = setInterval(() => { poll().catch((e) => console.warn('[clipboard]', e.message)); }, POLL_MS);
  console.log('[clipboard] recording started');
}
function stop() {
  if (timer) { clearInterval(timer); timer = null; console.log('[clipboard] recording stopped'); }
}
function isRunning() { return !!timer; }

async function poll() {
  if (busy || !deps) return;
  busy = true;
  try {
    // While the same image sits on the clipboard, re-read the (expensive) PNG only every third poll.
    imagePolls++;
    let snap = await snapshot({ readImage: last.kind !== 'image' || imagePolls % 3 === 0 });
    if (isConcealed(snap.types)) return;
    if (!snap.types.length) { last = { sig: '', kind: '' }; return; } // clipboard emptied
    let sig = signature(snap);
    if (!sig || sig === last.sig) return;
    if (last.kind === 'image' && !snap.png && !snap.text && !snap.files.length) return; // image skipped this round
    if (isOtherShape(sig)) { last = { sig, kind: '' }; return; }   // the leftover of a copy already filed

    // Something new: look at every shape it came in, so the ones not filed are recognised later.
    const full = await snapshot({ all: true });
    const fullSig = signature(full);
    if (fullSig) { snap = full; sig = fullSig; }
    noteOtherShapes(snap, sig);

    const s = deps.store.getSettings();
    if (snap.files.length) {
      last = { sig, kind: 'files' };
      await deps.workspace.ingestFiles(snap.files, { origin: 'clipboard', quiet: true });
    } else if (snap.text) {
      last = { sig, kind: 'text' };
      const trimmed = snap.text.trim();
      if (trimmed.length < (Number(s.clipboardMinChars) || 1)) return;
      if (deps.workspace.hasText(trimmed)) return; // copied out of the workspace itself
      await deps.workspace.ingestDrop({ text: trimmed }, { origin: 'clipboard', quiet: true });
    } else if (snap.png) {
      last = { sig, kind: 'image' };
      if (ignore.has(sig) || ignore.has('image:*next*')) {   // our own screenshot, already recorded
        ignore.delete(sig); ignore.delete('image:*next*');
        return;
      }
      await deps.workspace.ingestClipboardImage(snap.png);   // null = the same picture, already filed
    }
  } finally {
    busy = false;
  }
}

module.exports = { start, stop, isRunning, poll, snapshot, signature, signatures, noteOtherShapes, isOtherShape, ignoreNext };
