'use strict';
// Fetches the app's typefaces into assets/fonts and writes assets/fonts/fonts.css.
//
//   node scripts/fetch-fonts.js        (idempotent: a file already on disk is not fetched again)
//
// The app runs offline and must never fetch a font at runtime, so the files come down at install
// time (package.json postinstall) and every renderer page links the generated stylesheet. All five
// faces are OFL; they come from the @fontsource packages on jsDelivr, which ship each face cut into
// unicode-range slices -- Chromium then loads only the slices a page actually uses, which for the
// CJK faces is the difference between ~10 MB on disk and a few hundred KB in memory.
//
// Why these faces: see .claude/skills/paper-ui/SKILL.md ("字 · 两种文字，一张纸"). In one line:
// Latin first, then the CJK face designed to sit with it -- Source Sans / Source Serif are the
// Latin halves of 思源黑 / 思源宋, drawn by the same team.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'assets', 'fonts');
const FILES = path.join(OUT, 'files');
const CDN = 'https://cdn.jsdelivr.net/npm/';

// family: the name the app's CSS uses (the packages call the variable cuts "… Variable"; we do not).
// subsets: which unicode-range slices to keep; the CJK faces have no named subsets, so all of them.
const FACES = [
  { pkg: '@fontsource-variable/noto-sans-sc', ver: '5.2.5', css: ['index.css'], family: 'Noto Sans SC' },
  { pkg: '@fontsource-variable/noto-serif-sc', ver: '5.2.5', css: ['index.css'], family: 'Noto Serif SC' },
  { pkg: '@fontsource-variable/source-sans-3', ver: '5.2.5', css: ['index.css'], family: 'Source Sans 3', subsets: ['latin', 'latin-ext'] },
  { pkg: '@fontsource-variable/source-serif-4', ver: '5.2.5', css: ['index.css'], family: 'Source Serif 4', subsets: ['latin', 'latin-ext'] },
  { pkg: '@fontsource/ibm-plex-mono', ver: '5.2.5', css: ['400.css', '500.css', '600.css'], family: 'IBM Plex Mono', subsets: ['latin', 'latin-ext'] },
];

async function get(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return Buffer.from(await r.arrayBuffer());
}

// a handful at a time: the CJK faces are ~120 slices each
async function pool(items, n, fn) {
  const q = items.slice();
  const workers = Array.from({ length: n }, async () => { while (q.length) await fn(q.shift()); });
  await Promise.all(workers);
}

(async () => {
  fs.mkdirSync(FILES, { recursive: true });
  const out = ['/* Generated by scripts/fetch-fonts.js -- do not edit. Faces are OFL; see that script for why these. */'];
  let bytes = 0, fetched = 0, kept = 0;
  for (const face of FACES) {
    const blocks = [];
    for (const cssName of face.css) {
      const css = (await get(`${CDN}${face.pkg}@${face.ver}/${cssName}`)).toString('utf8');
      for (const block of css.match(/@font-face\s*\{[^}]*\}/g) || []) {
        const file = (block.match(/url\(\.\/files\/([^)]+\.woff2)\)/) || [])[1];
        if (!file) continue;
        if (face.subsets && !face.subsets.some((s) => file.includes(`-${s}-`))) continue;
        blocks.push({ file, block });
      }
    }
    await pool(blocks, 8, async ({ file }) => {
      const dst = path.join(FILES, file);
      if (fs.existsSync(dst)) { kept++; bytes += fs.statSync(dst).size; return; }
      const buf = await get(`${CDN}${face.pkg}@${face.ver}/files/${file}`);
      fs.writeFileSync(dst, buf);
      fetched++; bytes += buf.length;
    });
    out.push(`\n/* ---- ${face.family} (${face.pkg}@${face.ver}) ---- */`);
    for (const { block } of blocks) {
      out.push(block
        .replace(/font-family:\s*'[^']*'/, `font-family: '${face.family}'`)
        // drop the woff2-variations duplicate: one url per face is enough for Chromium
        .replace(/,\s*url\([^)]*\)\s*format\('woff2'\)/, '')
        .replace(/font-display:\s*swap/, 'font-display: block'));   // bundled: nothing to swap from
    }
    console.log(`${face.family}: ${blocks.length} slices`);
  }
  fs.writeFileSync(path.join(OUT, 'fonts.css'), out.join('\n') + '\n');
  console.log(`fonts: ${fetched} fetched, ${kept} already present, ${(bytes / 1048576).toFixed(1)} MB on disk -> ${path.relative(ROOT, OUT)}`);
})().catch((e) => { console.error('fetch-fonts:', e.message); process.exit(1); });
